version: '3.8'

services:
  proxy:
    image: nginx:alpine
    container_name: rutube_proxy
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    cap_add:
      - NET_ADMIN
    command: sh -c "ip route del default && ip route add default via 192.168.1.1 dev eth1 && nginx -g 'daemon off;'"
    networks:
      default:
      physical_net:
        ipv4_address: 192.168.1.199

  ngrok:
    image: ngrok/ngrok:latest
    container_name: rutube_ngrok
    restart: unless-stopped
    depends_on:
      - proxy
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: "http proxy:80 --log=stdout"
    networks:
      - default

networks:
  default:
  physical_net:
    driver: ipvlan
    driver_opts:
      parent: wlp44s0
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1


