server {
    listen 80;
    resolver 8.8.8.8 ipv6=off;

    location / {
        set $target $http_x_target_url;
        set $target_host $http_x_target_host;
        
        if ($target = "") {
            set $target "https://rutube.ru$request_uri";
            set $target_host "rutube.ru";
        }

        proxy_pass $target;
        proxy_set_header Host $target_host;
        proxy_set_header Origin "https://rutube.ru";
        proxy_set_header Referer "https://rutube.ru/";
        proxy_ssl_server_name on;
        proxy_set_header User-Agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";
        
        add_header 'Access-Control-Allow-Origin' '*';
    }
}
