settings:
  non_interactive: true
  log_file: "/var/log/ubuntuInstaller/install.log"
profile: "developer"
roles_enabled:
  - name: 0-base-system
  - name: 10-dev-tools
    vars:
      install_vscode: true
      install_pycharm: false
  - name: 20-docker
    enabled: true