settings:
  non_interactive: true
  log_file: "/var/log/ubuntuInstaller/install.log"
profile: "developer"
roles_enabled:
  - name: 0-base-system
  - name: 10-dev-tools
    vars:
      install_vscode: true
      install_pycharm: false
  - name: 20-docker
    enabled: true
  - name: 30-secure-default
  - name: 40-snap-apps
  - name: 50-dev-pack
  - name: 60-samsung-printer
  - name: 70-zerotier-client
  - name: 80-virtualbox