# ~/.config/yazi/yazi.toml

[manager]
ratio          = [ 1, 4, 3 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
linemode       = "none"
show_hidden    = false
show_symlink   = true
scrolloff      = 5

[preview]
wrap            = "yes"
tab_size        = 2
max_width       = 600
max_height      = 900
image_filter    = "triangle"
image_quality   = 75

[opener]
edit = [
	{ run = 'code "$@"', desc = "VS Code", orphan = true },
	{ run = '${EDITOR:-nano} "$@"', desc = "Terminal Editor", block = true },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open", orphan = true },
]
