settings:
  non_interactive: true
 log_file: "/var/log/ubuntuInstaller/install-server.log"
 create_snapshot: false # Создавать снапшот перед установкой критичных ролей
  remove_snapshots: true # Удалять созданные снапшоты после установки
profile: "server"
roles_enabled:
  - name: 0-base-system
  - name: 20-docker
    enabled: true