settings:
  non_interactive: true
  log_file: "/var/log/ubuntuInstaller/install-wsl.log"
  create_snapshot: false # Создавать снапшот перед установкой критичных ролей
  remove_snapshots: true # Удалять созданные снапшоты после установки
profile: "wsl"
roles_enabled:
 - name: 0-base-system
 - name: 10-dev-tools
   vars:
     install_vscode: false
     install_pycharm: false
 - name: 20-docker
   enabled: false

